const VEGGIE_API_URL = import.meta.env.VITE_VEGGIE_API_URL;
const CATEGORY_API_URL = import.meta.env.VITE_CATEGORY_API_URL;
const CATEGORY_FILTER_API_URL = import.meta.env.VITE_CATEGORY_FILTER_API_URL;
const SEARCH_API_URL = import.meta.env.VITE_SEARCH_PRODUCT_API_URL;
const DETAILS_API_URL = import.meta.env.VITE_PRODUCTS_DETAILS_API_URL;
const USER_API_URL = import.meta.env.VITE_USER_API_URL;
export default {
  VEGGIE_API_URL,
  CATEGORY_API_URL,
  CATEGORY_FILTER_API_URL,
  SEARCH_API_URL,
  DETAILS_API_URL,
  USER_API_URL,
};
